In [1]:
import pandas as pd

df = pd.read_csv("./data/subject-info.csv", sep=";", encoding="utf-8")
df.head()

,Patient ID,Follow-up period from enrollment (days),days_4years,Exit of the study,Cause of death,Age,Gender (male=1),Weight (kg),Height (cm),Body Mass Index (Kg/m2),...,Angiotensin-II receptor blocker (yes=1),Anticoagulants/antitrombotics (yes=1),Betablockers (yes=1),Digoxin (yes=1),Loop diuretics (yes=1),Spironolactone (yes=1),Statins (yes=1),Hidralazina (yes=1),ACE inhibitor (yes=1),Nitrovasodilator (yes=1)
0,P0001,2065,1460,NaN,0,58,1,83,163,"31,2",...,0,1,1,1,1,0,0,0,1,0
1,P0002,2045,1460,NaN,0,58,1,74,160,"28,9",...,1,1,1,0,0,0,1,0,0,0
2,P0003,2044,1460,NaN,0,69,1,83,174,"27,4",...,1,1,1,1,1,0,0,0,0,0
3,P0004,2044,1460,NaN,0,56,0,84,165,"30,9",...,1,1,1,0,1,1,0,0,0,0
4,P0005,2043,1460,NaN,0,70,1,97,183,29,...,0,1,1,0,1,0,1,0,1,1

In [2]:
print("Spalten vor der Verarbeitung:", df.columns.tolist())

Spalten vor der Verarbeitung: ['Patient ID', 'Follow-up period from enrollment (days)', 'days_4years', 'Exit of the study', 'Cause of death', 'Age', 'Gender (male=1)', 'Weight (kg)', 'Height (cm)', 'Body Mass Index (Kg/m2)', 'NYHA class', 'Diastolic blood  pressure (mmHg)', 'Systolic blood pressure (mmHg)', 'HF etiology - Diagnosis', 'Diabetes (yes=1)', 'History of dyslipemia (yes=1)', 'Peripheral vascular disease (yes=1)', 'History of hypertension (yes=1)', 'Prior Myocardial Infarction (yes=1)', 'Prior implantable device', 'Prior Revascularization', 'Syncope', 'daily smoking (cigarretes/day)', 'smoke-free time (years)', 'cigarettes /year', 'alcohol consumption (standard units)', 'Albumin (g/L)', 'ALT or GPT (IU/L)', 'AST or GOT (IU/L)', 'Normalized Troponin', 'Total Cholesterol (mmol/L)', 'Creatinine (?mol/L)', 'Gamma-glutamil transpeptidase (IU/L)', 'Glucose (mmol/L)', 'Hemoglobin (g/L)', 'HDL (mmol/L)', 'Potassium (mEq/L)', 'LDL (mmol/L)', 'Sodium (mEq/L)', 'Pro-BNP (ng/L)', 'Protein (g/L)', 'T3 (pg/dL)', 'T4 (ng/L)', 'Troponin (ng/mL)', 'TSH (mIU/L)', 'Urea (mg/dL)', 'Signs of pulmonary venous hypertension (yes=1)', 'Cardiothoracic ratio', 'Left atrial size (mm)', 'Right ventricle contractility (altered=1)', 'Right ventricle end-diastolic diameter (mm)', 'LVEF (%)', 'Mitral valve insufficiency ', 'Mitral flow pattern', 'Left ventricular posterior wall thickness (mm)', 'Septal thickness (mm)', 'Left ventricle end-diastolic diameter (mm)', 'Left ventricle end-systolic diameter (mm)', 'Hig-resolution ECG available', 'ECG rhythm ', 'Q-waves (necrosis, yes=1)', 'PR interval (ms)', 'QRS duration (ms)', 'QRS > 120 ms ', 'QT interval (ms)', 'QT corrected ', 'Average RR (ms) ', 'Left ventricular hypertrophy (yes=1)', 'Intraventricular conduction disorder', 'Holter available', 'Holter onset (hh:mm:ss)', 'Holter  rhythm ', 'minimum RR (ms) ', 'Average RR (ms)', 'maximum RR (ms)', 'RR range (ms)', 'Number of ventricular premature beats in 24h', 'Extrasystole couplets ', 'Ventricular Extrasystole', 'Ventricular Tachycardia', 'Number of ventricular premature contractions per hour', 'Non-sustained ventricular tachycardia (CH>10)', 'Number of supraventricular premature beats in 24h', 'Paroxysmal supraventricular tachyarrhythmia', 'Longest RR pause (ms)', 'Bradycardia', 'SDNN (ms)', 'SDANN (ms)', 'RMSSD (ms)', 'pNN50 (%)', 'Calcium channel blocker (yes=1)', 'Diabetes medication (yes=1)', 'Amiodarone (yes=1)', 'Angiotensin-II receptor blocker (yes=1)', 'Anticoagulants/antitrombotics  (yes=1)', 'Betablockers (yes=1)', 'Digoxin (yes=1)', 'Loop diuretics (yes=1)', 'Spironolactone (yes=1)', 'Statins (yes=1)', 'Hidralazina (yes=1)', 'ACE inhibitor (yes=1)', 'Nitrovasodilator (yes=1)']

In [3]:
if "Average RR (ms)" in df.columns:
    print(df["Average RR (ms)"].head())  # Zeigt die ersten 5 Zeilen
    print(df["Average RR (ms)"].shape)   # PrÃ¼ft, ob es 2 Spalten gibt

0    984.0
1    682.0
2    667.0
3    845.0
4    811.0
Name: Average RR (ms), dtype: float64
(992,)

In [4]:
print(df.loc[:, df.columns.duplicated(keep=False)])

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[992 rows x 0 columns]

In [5]:
df.head()

,Patient ID,Follow-up period from enrollment (days),days_4years,Exit of the study,Cause of death,Age,Gender (male=1),Weight (kg),Height (cm),Body Mass Index (Kg/m2),...,Angiotensin-II receptor blocker (yes=1),Anticoagulants/antitrombotics (yes=1),Betablockers (yes=1),Digoxin (yes=1),Loop diuretics (yes=1),Spironolactone (yes=1),Statins (yes=1),Hidralazina (yes=1),ACE inhibitor (yes=1),Nitrovasodilator (yes=1)
0,P0001,2065,1460,NaN,0,58,1,83,163,"31,2",...,0,1,1,1,1,0,0,0,1,0
1,P0002,2045,1460,NaN,0,58,1,74,160,"28,9",...,1,1,1,0,0,0,1,0,0,0
2,P0003,2044,1460,NaN,0,69,1,83,174,"27,4",...,1,1,1,1,1,0,0,0,0,0
3,P0004,2044,1460,NaN,0,56,0,84,165,"30,9",...,1,1,1,0,1,1,0,0,0,0
4,P0005,2043,1460,NaN,0,70,1,97,183,29,...,0,1,1,0,1,0,1,0,1,1

In [6]:
print(df.head())

  Patient ID  Follow-up period from enrollment (days)  days_4years  \
0      P0001                                     2065         1460
1      P0002                                     2045         1460
2      P0003                                     2044         1460
3      P0004                                     2044         1460
4      P0005                                     2043         1460

   Exit of the study  Cause of death Age  Gender (male=1)  Weight (kg)  \
0                NaN               0  58                1           83
1                NaN               0  58                1           74
2                NaN               0  69                1           83
3                NaN               0  56                0           84
4                NaN               0  70                1           97

   Height (cm) Body Mass Index (Kg/m2)  ...  \
0          163                    31,2  ...
1          160                    28,9  ...
2          174                    27,4  ...
3          165                    30,9  ...
4          183                      29  ...

   Angiotensin-II receptor blocker (yes=1)  \
0                                        0
1                                        1
2                                        1
3                                        1
4                                        0

   Anticoagulants/antitrombotics  (yes=1)  Betablockers (yes=1)  \
0                                       1                     1
1                                       1                     1
2                                       1                     1
3                                       1                     1
4                                       1                     1

   Digoxin (yes=1)  Loop diuretics (yes=1)  Spironolactone (yes=1)  \
0                1                       1                       0
1                0                       0                       0
2                1                       1                       0
3                0                       1                       1
4                0                       1                       0

   Statins (yes=1)  Hidralazina (yes=1)  ACE inhibitor (yes=1)  \
0                0                    0                      1
1                1                    0                      0
2                0                    0                      0
3                0                    0                      0
4                1                    0                      1

   Nitrovasodilator (yes=1)
0                         0
1                         0
2                         0
3                         0
4                         1

[5 rows x 103 columns]